# Generated by Django 5.0.2 on 2024-03-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0008_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='unti_price',
            new_name='unit_price',
        ),
    ]
